### ISSUE TITLE
Deployed app but not able to access webapp 

### ISSUE THREAD

**Issue by vishnugonela** [shhdharmen/gitalytics#11]
**Describe the bug**

Deployed app successfully, but not able to access webapp and no documentation on this.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shhdharmen** [comment]
This project is not actively maintained. If you need help, reach out to me on discord at shhdharmen.
